### ISSUE TITLE
TV-Archiver won't work an all Series Tags

### ISSUE THREAD

**Issue by tpexer** [silv3rr/slv-arch#1]
Hiho, 

the archiver is awesome, but on some tags for series it doesnt work correct.

e.g. if the series is tagged like Series.S01.E01a.xxx. or if there isnt a Season Tag, Like Series.E01.xxx.xxx.

Could this be fixed ? 

i would appreciate that. 

Greets

**Comment by silv3rr** [comment]
Hi,

Probably this incorrect regexp prevents moving `.E01..*` 
https://github.com/silv3rr/slv-arch/blob/18febaa3e24ec4df555b22838fc57c0a11cae9d6/slv-arch.sh#L329

It should be:
`-e 's/\.\(E[0-9]\+\)\..*//gi' \`

To add E01[a-c] change L325 to:
`                                -e 's/\.\(S[0-9]\+E[0-9]\+[a-z]\?\)\..*//gi' \`

I'll add it to next update
